# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

exporters:
  otlp/honeycomb:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "<HONEYCOMB_API_KEY>"
      "x-honeycomb-dataset": "webstore-metrics"
processors:
  attributes:
    include:
      match_type: strict
      services:
        - frontend-proxy
    actions:
      - key: "net.component"
        value: "proxy"
        action: insert
service:
  pipelines:
    traces:
      processors: [attributes, batch]
      exporters: [otlp, debug, spanmetrics, otlp/honeycomb]
    metrics:
      exporters: [oltphttp/prometheus, debug, otlp/honeycomb]
    logs:
      exporters: [opensearch, debug, otlp/honeycomb]
